### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by jflory7** [FOSSRIT/connect-rit#3]
Hey @Qalthos, some of us in RITlug (@abkahrs, @Serubin, others) were wanting to look at using this script for a project to revive the RIT Linux remix, but we weren't sure how to move forward with using this script since there isn't any license. Would you be able to add a LICENSE to the repository so we can responsibly reuse this code and attribute credit? Thanks! 😄

**Comment by axk4545** [comment]
@Qalthos @abkahrs is now me @axk4545 any movement on this?

**Comment by Qalthos** [comment]
First, this isn't actually mine, this actually comes from a time before FOSS@RIT was on GitHub (gasp, shock!) and I'm not actually sure on original author, I want to say @jlew, but I blame all the code I wrote before he graduated on him anyway so I might be misremembering.

That said (and IANAL), this code was given away freely without thought of restriction or attribution, and the intended license is probably somewhere between CC0 and MIT, with my bet being on the former. If you really want to be safe, I would ask someone else to reimplement it, and as long as you really want to keep the requirement of passwords not being stored on disk, I imagine you'd come up with something almost exactly identical to this file.

**Comment by jlew** [comment]
This looks like the code I wrote for the XO laptop as at that time the network manager didn't support Enterprise configurations.

So this script was installed on the xo's to get on the network.

Feel free to licence it coveter like consistently with other foss@rit scripts

**Comment by Serubin** [comment]
Added MIT license in pull request #4

**Comment by axk4545** [comment]
@Qalthos @jlew @Serubin @jflory7 I think for our use case we would store the resulting file in the normal system location rather than external media.
